name: Publish to CurseForge
'on':
  release:
    types:
      - created
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml && echo "FINAL_NAME=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout)" >> $GITHUB_ENV
      - name: CurseForge
        uses: itsmeow/curseforge-upload@v3
        with:
          token: '${{ secrets.CURSEFORGE_TOKEN }}'
          project_id: 635189
          game_endpoint: minecraft
          file_path: 'target/${{ env.FINAL_NAME }}.jar'
          changelog: '${{ github.event.release.body }}'
          changelog_type: markdown
          display_name: '${{ github.event.release.tag_name }}'
          game_versions: '9190,8849,8503,7915,7667,7330,7105,6588,630,591,585,531'
          release_type: release
          relations: 'vault:requiredDependency'
