on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: maven
          package-name: CryptoMarket
          token: ${{ secrets.PAT_TOKEN }}
          fork: true